apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/Creditas/oi
    creditas.io/expose-type: internal
  description: Test Application
  labels:
    creditas.io/language: Python
    creditas.io/tribe: Foundation
  name: vanessitas
  tags:
  - service
spec:
  lifecycle: experimental
  owner: foundation-devtools
  providesApis:
  - vanessitas-api
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  description: API for vanessitas
  name: vanessitas-api
spec:
  definition: "openapi: \"3.0.0\"\ninfo:\n  version: 1.0.0\n  title: Artist API\n\
    \  license:\n    name: MIT\nservers:\n  - url: http://artist.spotify.net/v1\n\
    paths:\n  /artists:\n    get:\n      summary: List all artists"
  lifecycle: production
  owner: foundation-devtools
  system: vanessitas
  type: openapi
