version: '3'

services:
  credit-analyzer:
    build: .
    ports:
      - 5000:8080
  
  loan-application:
    image: creditas/mle-challenge-loan-application
    environment:
      time_per_request: 0.1
    ports: 
      - 5001:8080
    depends_on:
      - credit-analyzer
